services:
  # === БАЗА ДАННЫХ ===
  db:
    image: postgres:16-alpine
    container_name: ecommerce-auth-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

  # === KAFKA ===
  kafka:
    image: apache/kafka:3.7.0
    container_name: ecommerce-kafka
    hostname: kafka
    ports:
      - "9092:9092"           # Для клиентов (наши сервисы)
      - "29092:29092"         # Для внутренней связи
      - "9999:9999"           # Только JMX Exporter (для Prometheus)
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093,INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_JMX_PORT: 9998
      KAFKA_JMX_HOSTNAME: localhost

      KAFKA_OPTS: "-javaagent:/jmx_exporter/jmx_prometheus_javaagent.jar=9999:/etc/kafka/jmx-exporter.yml"
    volumes:
      - kafka_data:/var/lib/kafka/data
      - ./monitoring/kafka-jmx-exporter.yml:/etc/kafka/jmx-exporter.yml
      - ./monitoring/jmx_prometheus_javaagent.jar:/jmx_exporter/jmx_prometheus_javaagent.jar:ro
    networks:
      - default
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  # === KAFKA UI ===
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ecommerce-kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - default

  # === PROMETHEUS ===
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: ecommerce-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - default

  # === GRAFANA ===
  grafana:
    image: grafana/grafana:10.0.0
    container_name: ecommerce-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - default

  # === AUTH SERVICE  ===
  auth-service:
    build: ./services/auth-service/auth-service
    container_name: ecommerce-auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=auth-service
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - default

  # === PRODUCT SERVICE ===
  product-service:
    build: ./services/product-service
    container_name: ecommerce-product-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=product-service
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - db
      - kafka
    networks:
      - default

  # === NOTIFICATION SERVICE ===
  notification-service:
    build: ./services/notification-service
    container_name: ecommerce-notification-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_APPLICATION_NAME=notification-service
      - SERVER_PORT=8083
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - kafka
    networks:
      - default

volumes:
  pgdata:
  kafka_data:
  prometheus_data:
  grafana_data:

networks:
  default:
    driver: bridge