server:
  port: 8091

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # 🔐 Auth Service
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/gateway/auth/**
              filters:
                - StripPrefix=2

            # 📦 Product Service
            - id: product-service
              uri: http://localhost:8082
              predicates:
                - Path=/gateway/product/**
              filters:
                - StripPrefix=2

            # 🛒 Order Service
            - id: order-service
              uri: http://localhost:8084
              predicates:
                - Path=/gateway/order/**
              filters:
                - StripPrefix=2

            # 🔔 Notification Service
            - id: notification-service
              uri: http://localhost:8083
              predicates:
                - Path=/gateway/notification/**
              filters:
                - StripPrefix=2
          globalcors: # <-- cors теперь здесь
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: [ GET, POST, PUT, DELETE, OPTIONS ]
                allowedHeaders: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
