# Server config
spring.application.name=notification-service
server.port=8083

# Kafka Config
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

# Actuator
management.endpoints.web.exposure.include=health,info